// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBVjnrQV_3gI9HeTD_Qv68uH_tc8pOwJ78',
    appId: '1:375821209917:web:d6fc8a24ba58f2606d7554',
    messagingSenderId: '375821209917',
    projectId: 'my-life-hint',
    authDomain: 'my-life-hint.firebaseapp.com',
    storageBucket: 'my-life-hint.appspot.com',
    measurementId: 'G-V7YJ0H8XPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVFevOf3Qhu9vU_fBVUm4a3TAgBy5HANE',
    appId: '1:375821209917:android:74f935009d0731b56d7554',
    messagingSenderId: '375821209917',
    projectId: 'my-life-hint',
    storageBucket: 'my-life-hint.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX2zfln0oqTePzZS6YyTV_guAcGs-uG8Q',
    appId: '1:375821209917:ios:adfc52c8e2fa85b56d7554',
    messagingSenderId: '375821209917',
    projectId: 'my-life-hint',
    storageBucket: 'my-life-hint.appspot.com',
    iosBundleId: 'com.deepakumar452005.quizMaker',
  );
}
